<Project>
  <PropertyGroup>
    <PackageIcon>Icon.png</PackageIcon>
    <PackageProjectUrl>https://www.monogame.net/</PackageProjectUrl>
    <RepositoryUrl>https://github.com/MonoGame/MonoGame</RepositoryUrl>
    <Authors>MonoGame Team</Authors>
    <PackageLicenseExpression>MS-PL</PackageLicenseExpression>
    <VersionPrefix>3.8.5</VersionPrefix>
    <VersionSuffix>local.3</VersionSuffix>
  </PropertyGroup>

  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)Images\Icon.png" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>

